version: "3"
services:
  datastore:
    image: busybox
    volumes:
      - "postgres-data:/var/lib/postgres"
      - "redis-data:/data"
      - "bundle_install:/app/vendor/bundle"
      - "bundle:/app/.bundle"
      - "node_modules:/app/node_modules"

  postgres:
    image: postgres
    networks:
      - default
    volumes:
      - "postgres-data:/var/lib/postgres"

  redis:
    image: redis:alpine
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    volumes:
      - .:/app
    volumes:
      - "postgres-data:/var/lib/postgres"
      - "redis-data:/data"
      - "bundle_install:/app/vendor/bundle"
      - "bundle:/app/.bundle"
      - "node_modules:/app/node_modules"
    networks:
      - default
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
